blog/urls.py
from django.conf.urls import url

from .views import (
    home,
    blog_post,

)

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', blog_post, name="blog_post"),
    url(r'^$', home, name='home'),
]

justjob5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    # url(r'^backoffice24/', include('backoffice24.urls',
    #     namespace='backoffice24')),
]


urlpatterns += i18n_patterns(
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^employer/', include('employer.urls', namespace='employer')),
    url(r'^', include('main_pages.urls', namespace='main')),
)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, redirect


def home(request):
    prefix = 'en'
    if request.LANGUAGE_CODE == 'ru':
        prefix = 'ru'
    elif request.LANGUAGE_CODE == 'hu':
        prefix = 'hu'
    elif request.LANGUAGE_CODE == 'uk':
        prefix = 'uk'
    else:
        prefix = 'en'
    template = "blog/{}/home.html".format(prefix)
    return render(request, template, {})


def blog_post(request, slug):
    prefix = 'en'
    if request.LANGUAGE_CODE == 'ru':
        prefix = 'ru'
    elif request.LANGUAGE_CODE == 'hu':
        prefix = 'hu'
    elif request.LANGUAGE_CODE == 'uk':
        prefix = 'uk'
    else:
        prefix = 'en'

    if slug == 'fun-facts-part1':
        template = "blog/{}/fun_facts1.html".format(prefix)
    elif slug == 'fun-facts-part2':
        template = "blog/{}/fun_facts2.html".format(prefix)
    elif slug == 'hungarian-language':
        template = "blog/{}/about_lang.html".format(prefix)
    else:
        return redirect('blog:home')
    return render(request, template, {})

blog/templates/blog/uk/about_lang.html
{% extends "base_layout.html" %}
{% load staticfiles %}


{%  block title %}Тонкощі угорської мови - {%  endblock %}

{%  block titlebar %}
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo.jpg' %});">
    <div class="container">

        <div class="sixteen columns">
            <h2>Тонкощі угорської мови</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>Ви тут:</li>
                    <li><a href="{% url 'blog:home' %}">Блог</a></li>
                    <li>Тонкощі угорської мови</li>
                </ul>
            </nav>
        </div>

    </div>
</div>

{%  endblock %}


{%  block content %}
<!-- Content
================================================== -->
<div class="container">

    <!-- Blog Posts -->
    <div class="eleven columns">
        <div class="padding-right">

            <!-- Post -->
            <div class="post-container">
                <div class="post-img"><img src="{% static 'images/about_lang.jpg' %}" alt=""></div>
                <div class="post-content">
                    <h1>Тонкощі угорської мови</h1>
                    <div class="meta-tags">
                        <span>1 Січня 2018</span>
                    </div>
                    <div class="clearfix"></div>
                    <div class="margin-bottom-25"></div>

                    <p>Угорщина - дуже цікава країна з давньою і насиченою історією. І немає нічого дивного в тому, що її народ спілкується надзвичайно багатою мовою.</p>

                    <div class="post-quote">
                        <span class="icon"></span>
                        <blockquote>
                            Угорська мова входить в число найскладніших мов, поряд з японською, арабською і китайською. Але, навіть не зважаючи на це, кількість людей, бажаючих її вивчити зростає з кожним роком.
                        </blockquote>
                    </div>

                    <p>В першу чергу, знання угорської мови надає перевагу при працевлаштуванні в міжнародні компанії або при переїзді в Європу, адже сучасних роботодавців вже не здивуєш навіть досконалим володінням англійської чи німецької.</p>
                    <p>По-друге, згадаємо той факт, що туристичний напрямок Угорщини активно розвивається з кожним днем. Безліч бальнео-санаторіїв, курортів, туристичних маршрутів, а також красива природа, невисокі ціни і смачна кухня — в Угорщині є все необхідне для ідеального відпочинку. Однак, англійською мовою в Угорщині володіє переважно молодь, старші ж покоління здебільшого не розмовляють жодною мовою, окрім рідної угорської. А це означає, що під час візиту в цю дивовижну країну, Вам стануть в нагоді навіть найелементарніші знання угорської.
                    </p>
                    <p>
                        І, звичайно ж, вивчення такої незвичної для нас, словʼян, мови захоплює все більше поліглотів, для яких структура і особливе звучання угорської це своєрідний виклик.
                    </p>
                    <p>
                        Історія виникнення мови, як і самої держави бере свій початок з Азії. Угорська мова повністю відрізняється від діалектів, якими розмовляють сусідні держави з індоєвропейської мовної сім'ї. Фактично, угорська мова виникла в уральському регіоні Азії і відноситься до угро-фінської мовної групи, що свідчить про те, що найближчі сучасні родичі угорської це фінська і естонська мови.
                    </p>
                    <p>
                        За своє довге існування угорська мова розвивалася разом з народом і підпадала під вплив безлічі інших мов, що належали як ворожим племенам, так і дружнім сусідам. Угорська мова ввібрала в себе потроху від кожної мови, з якою контактувала. В угорській мові ми знаходимо сліди запозичень англіцизмів, галліцізмов і якусь схожість з німецькою і турецькою мовами. Важливий внесок в розвиток і формування угорської мови мали і слов'янські мови. Однак, зберігаючи вірність своєму стародавньому корінню, угорська мова містить колосальні 68% від своїх початкових слів. Порівняйте це з чотирма відсотками, що залишилися в англійській мові, або п'ятьма відсотками, що збереглися в івриті, і цей масштаб вразить ще більше.
                    </p>
                    <p>
                        Угорською розмовляють приблизно 17 млн осіб у всьому світі. Велика частина мовців проживає в Карпатському басейні: 10 млн - в Угорщині 2,5 млн - в Румунії, 1 млн - в Словаччині, 700 000 - на території колишньої Югославії, 250 000 - на території Карпат, 50 000 - в Австрії, і близько 300 000 в інших європейських країнах.
                    </p>
                    <h3 class="margin-top-35 margin-bottom-25">                 
                        Так що ж робить угорську мову настільки складною у вивченні?
                   </h3>
                   <p>
                        У той час як думки розходяться, більшість погоджуються з тим, що угорська мова перебуває в рейтингу "Топ 10 складних мов світу" завдяки своїм 26 відмінками і численним складним правилам.
                    </p>
                    <p>
                        Ще одна причина ховається в самому алфавіті. В угорській мові є 40 букв, 14 з яких голосні. Окрім основних голосних "a, e, i, o, u", угорська мова також включає в себе ще 9 варіацій: á, é, í, ó, ö, ő, ú, ü, ű. Вимова кожної з цих літер відрізняється лише протяжністю та мʼякістю, але може повністю змінити зміст слова. Що ж стосується приголосних, тут теж маємо невелику особливість. В угорському алфавіті вже зібрані деякі буквосполучення, що позначають певний звук. Цю закономірність слід вивчити ще на початку знайомства з угорською мовою. З найцікавіших виділимо незвичні нам букви "gy" [дь], "sz" [с], "zs" [ж], "cs" [ч], і "ly", що є еквівалентом нашого [й].
                    </p>
                    <p>
                        Характерна риса угорської мови це специфіка словотвору. Слова здебільшого утворюються методом аглютинації ( "приклеювання"). Наприклад, те, що в українській ми висловлюємо за допомогою прийменника, в угорської додається до кінця слова як відмінкове закінчення. Закінченнями, суфіксами, префіксами і приставками позначені в угорській також обставини місця і часу, та багато іншого. В якості яскравого прикладу візьмемо слово "barátainkról", що перекладемо словосполученням "про наших друзів".
                    </p>
                    <p>
                        Завдяки цьому "Суфіксальному нанизуванню" угорської мови, в 1996 році в Книгу рекордів Гіннеса було внесено найдовше слово, що складалось з 44 букв. У наш час одне з лідерів серед найдовших слів без дефісів займає майже цілий рядок - "folyamatellenőrzésiügyosztályvezetőhelyettesképesítésvizsgálat" (62 літери) - що приблизно означатиме "запит про кваліфікацію заступника начальника відділу управління процесами".
                    </p>
                    <p>
                        Як бачимо, слова угорської мови нерідко виходять дуже довгими. Щоб прочитати те чи інше слово, часто доводиться ділити його на частини або ж на склади. Як правило, наголос падає на перший склад, але в особливо довгих словах існують і побічні наголоси, що розставляються на кожному непарному складі (першому, третьому, п'ятому, сьомому).
                    </p>
                    <p>
                        Отож, так — угорська мова це справжня головоломка, і не випадково знаменитий кубик Рубіка був винайдений саме в Угорщині. І в той же час, як тільки зайві відмовки були відкинуті, і "мова поглинає з головою", обов'язково настає час приємного здивування і навіть зачарування гармонією і логікою цієї надзвичайної мови.
                    </p>
                    <p>
                        Ми щиро бажаємо Вам не боятися неповторності угорської мови. Спробуйте вивчити декілька граматичних структур і побутових фраз, і неодмінно приїжджайте практикуватися в Угорщину!
                    </p>
                    <p>
                        І наостанок, давайте разом розучимо відому крилату фразу: "Вчитися, вчитися і ще раз вчитися!", що в перекладі угорською: "Tanulni, tanulni és még egyszer tanulni!"
                    </p>
                    
                </div>
            </div>

            <!-- Comments -->
            


            <div class="clearfix"></div>
            <div class="margin-top-35"></div>


            <!-- Add Comment -->
            
        </div>
    </div>
    <!-- Blog Posts / End -->


    <!-- Widgets -->
    <div class="five columns blog">
       {% include 'blog/widget_sidebar_posts.html' %}
       <div class="clearfix"></div>
        <div class="margin-bottom-40"></div>
    </div><!-- Widgets / End -->


</div>
{%  endblock %}

blog/templates/blog/uk/fun_facts1.html
{% extends "base_layout.html" %}
{% load staticfiles %}


{%  block title %}Те, чого ви не знали про Угорщину (частина 1) - {%  endblock %}

{%  block titlebar %}
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo.jpg' %});">
    <div class="container">

        <div class="sixteen columns">
            <h2>Те, чого ви не знали про Угорщину (частина 1)</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>Ви тут:</li>
                    <li><a href="{% url 'blog:home' %}">Блог</a></li>
                    <li>Те, чого ви не знали про Угорщину (частина 1)</li>
                </ul>
            </nav>
        </div>

    </div>
</div>

{%  endblock %}


{%  block content %}
<!-- Content
================================================== -->
<div class="container">

    <!-- Blog Posts -->
    <div class="eleven columns">
        <div class="padding-right">

            <!-- Post -->
            <div class="post-container">
                <div class="post-img"><img src="{% static 'images/fun_facts1.jpg' %}" alt=""></div>
                <div class="post-content">
                    <h1>Те, чого ви не знали про Угорщину (частина 1)</h1>
                    <div class="meta-tags">
                        <span>3 Січня 2018</span>
                    </div>
                    <div class="clearfix"></div>
                    <div class="margin-bottom-25"></div>
                    <p>
                        1. Англійська назва "Hungary" (Угорщина) походить від Середньовічного латинського Hungaria, і перекладається як "Земля гунів". Назву побудовано з етнонімів (H)ungarī, Ungrī, Ugrī, які використовувалися середньовічними письменниками при згадці як самої країни Угорщини, так і її жителів. Згідно іншого джерела, назва започаткована від давньотурецьких слів "On ogur", що в перекладі означає "десять стріл" або "десять народів".
                    </p><p>
                        2. Усередині країни не вживається назва "Hungary". Жителі Угорщини називають себе Magyar (до речі, правильно "модьор", а не "мадяр"), а саму країну Magyarország (букв. "Країна угорців"). Національна мова Magyar є прямим нащадком мови, якою розмовляли гуни. В Європі є лише дві схожі мови: фінська (Suomi) і естонська(Eesti keel).
                    </p><p>
                        3. В угорській мові є 14 голосних букв. Десять літер, що передають голосні звуки української  мови - це ще не багато. Окрім основних голосних звуків: "a, e, i, o, u", угорська мова також включає в себе ще 9 варіацій: á, é, í, ó, ö, ő, ú, ü, ű. Вимова кожної з цих літер не набагато відрізняється, але може повністю змінити зміст слова.
                    </p><p>
                        4. Протягом століть корона Святого Іштвана, національний символ і священна реліквія Угорщини, неодноразово викрадалася. У 1978 році корона великого короля знову повернулася в Угорщину, і з тих пір разом з іншими королівськими регаліями - державою, скіпетром і клятвеним мечем зберігається в будівлі парламенту Будапешта. "Імʼям корони Святого Іштвана" — проголошується щоразу, коли в Угорщині твориться правосуддя.
                    </p><p>
                        5. Будівлю угорського парламенту в Будапешті було побудовано до святкування тисячоліття Угорщини в 1896 році. У будівництві використалося не менше 40 кг твердого золота. Висота будівлі становить 96 м, як і базиліка Святого Іштвана, це найвищі історичні будівлі Будапешта. Будапештський парламент це 3-тя за величиною будівля парламенту в світі, після лондонського Вестмінстера і парламенту Румунії.
                    </p><p>
                        6. Угорщина підтримує купальні традиції, які сягають до римських часів. У країні налічується близько 1500 купалень і курортів, 450 з яких громадські.
                    </p><p>
                        7. Число "96" наділене особливим значенням в Угорщині. Перший король модьорів, Арпад, був обраний в 896 році, при заснуванні угорської держави. Перше метро Будапешта було побудовано в 1896, до святкування  тисячолітньої річниці країни. Відповідно до закону, найвищі будівлі в Будапешті повинні перевищувати 96 футів у висоту, а виконання національного гімну Угорщини займатиме лише 96 секунд, якщо заспівати його в правильному темпі.
                    </p><p>
                        8. До речі про метро. Лінія метро в Будапешті стала першою в континентальній Європі, і другою найстаршою гілкою підземного транспорту в світі після Лондонського метрополітену.
                    </p><p>
                        9. Найбільша в світі геотермальна печерна система знаходиться в Угорщині. Вона розташована під землею в Будапешті. Також нещодавно було виявлене найбільше в Європі підземне озеро, і воно знаходиться під горою Геллерт в Будапешті.
                    </p><p>
                        10. Озеро Балатон - друге за величиною озеро в Європі і найбільше в Центральній Європі. Його також називають "Угорським морем". Розмір озера Балатон становить 77 км в довжину і від 3 до 14 км в ширину. Загальна площа озера 601 кв. км.
                    </p><p>
                        11. У Будапешті знаходиться найбільша в Європі і друга за величиною в світі синагога. Знаменита Будапештська Велика синагога на вулиці Дохань може вміщати до 3000 чоловік.
                    </p><p>
                        12. Угорщина була єдиною країною, яка провела національний референдум щодо вступу до НАТО в 1999 році.
                    </p><p>
                        13. У Будапешті є легенда в якій мовиться, що якщо доторкнутися до ручки анонімної статуї в парку біля площі Героїв, можна стати великим письменником. Статуя трохи схожа на похмурого женця, але, існує думка, що цей анонім є літописцем угорського короля Бейли.
                    </p><p>
                        14. В Угорщині, коли люди пишуть свої імена або представляються публіці, вони в першу чергу озвучать своє прізвище, і лише потім ім'я.
                    </p><p>
                        15. Раніше в Угорщині батьки були зобов'язані називати свою дитину згідно попередньо затвердженого списку імен. Тобто якщо мати або батько хотіли назвати свою дитину ім'ям, не зазначеним у цьому списку, вони повинні були подати заявку в Науково-дослідний інститут лінгвістики Угорської академії наук і сподіватися, що їх заявку затвердять.
                    </p><p>
                        16. З 2007 року угорці отримали 13 Нобелівських премій, чим перевершили досягнення Японії, Китаю, Індії, Австралії і Іспанії.
                    </p>
                                        
                </div>
            </div>

            <!-- Comments -->
            


            <div class="clearfix"></div>
            <div class="margin-top-35"></div>


            <!-- Add Comment -->
            
        </div>
    </div>
    <!-- Blog Posts / End -->


    <!-- Widgets -->
    <div class="five columns blog">
       {% include 'blog/widget_sidebar_posts.html' %}
       <div class="clearfix"></div>
        <div class="margin-bottom-40"></div>
    </div><!-- Widgets / End -->



</div>
{%  endblock %}

blog/templates/blog/uk/home.html
{% extends "base_layout.html" %}
{% load staticfiles %}

{%  block title %} Блог - {%  endblock %}

{%  block titlebar %}
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo.jpg' %});">
    <div class="container">

        <div class="sixteen columns">
            <h2>Блог</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>Останні новини та Цікаві факти про Угорщину</li>
                </ul>
            </nav>
        </div>

    </div>
</div>

{%  endblock %}


{%  block content %}

<!-- Content
================================================== -->
<div class="container">

    <!-- Blog Posts -->
    <div class="eleven columns">
        <div class="padding-right">

            <!-- Post -->
            <div class="post-container">
                <div class="post-img"><a href="{% url 'blog:blog_post' slug='fun-facts-part2' %}"><img src="{% static 'images/fun_facts2.jpg' %}" alt=""></a><div class="hover-icon"></div></div>
                <div class="post-content">
                    <a href="{% url 'blog:blog_post' slug='fun-facts-part2' %}"><h3>Те, чого ви не знали про Угорщину (частина 2)</h3></a>
                    <div class="meta-tags">
                        <span>5 Січня 2018</span>
                        <span><a href="{% url 'blog:blog_post' slug='fun-facts-part2' %}"> </a></span>
                    </div>
                    <p>Угорщина є однією з найстаріших країн Європи. Заснування Угорщини датується 896 роком, задовго до Франції, Німеччини чи Англії. Серед угорських винаходів варто відмітити безпечні сірники Яноша Іріні (зразок сучасних сірників), кубик Рубіка (Ерне Рубік), криптонова лампа розжарювання Імре Броді (сучасна електрична лампочка) і відкриття вітамінів B6, рибофлавіну і біотину (Пол Дьордь). Ще декілька видатних винаходів були зроблені угорцями, які покинули країну до Другої світової війни, серед них голографія (Денніс Габор), кулькова ручка (Ласло Біро), теорія водневої бомби (Едвард Теллер) і мова програмування BASIC (Джон Кемени і Томас Е. Курц).</p>
                    <a class="button" href="{% url 'blog:blog_post' slug='fun-facts-part2' %}">Читати</a>
                </div>
            </div>

            <!-- Post -->
            <div class="post-container">
                <div class="post-img"><a href="{% url 'blog:blog_post' slug='fun-facts-part1' %}"><img src="{% static 'images/fun_facts1.jpg' %}" alt=""></a><div class="hover-icon"></div></div>
                <div class="post-content">
                    <a href="{% url 'blog:blog_post' slug='fun-facts-part1' %}"><h3>Те, чого ви не знали про Угорщину (частина 1)</h3></a>
                    <div class="meta-tags">
                        <span>3 Січня 2018</span>
                        <span><a href="{% url 'blog:blog_post' slug='fun-facts-part1' %}"> </a></span>
                    </div>
                    <p>Англійська назва "Hungary" (Угорщина) походить від Середньовічного латинського Hungaria, і перекладається як "Земля гунів". Назву побудовано з етнонімів (H)ungarī, Ungrī, Ugrī, які використовувалися середньовічними письменниками при згадці як самої країни Угорщини, так і її жителів. Згідно іншого джерела, назва започаткована від давньотурецьких слів "On ogur", що в перекладі означає "десять стріл" або "десять народів".</p>
                    <a class="button" href="{% url 'blog:blog_post' slug='fun-facts-part1' %}">Читати</a>
                </div>
            </div>

            <!-- Post -->
            <div class="post-container">
                <div class="post-img"><a href="{% url 'blog:blog_post' slug='hungarian-language' %}"><img src="{% static 'images/about_lang.jpg' %}" alt=""></a><div class="hover-icon"></div></div>
                <div class="post-content">
                    <a href="{% url 'blog:blog_post' slug='hungarian-language' %}"><h3>Тонкощі угорської мови</h3></a>
                    <div class="meta-tags">
                        <span>1 Січня 2018</span>
                        <span><a href="{% url 'blog:blog_post' slug='hungarian-language' %}"> </a></span>
                    </div>
                    <p>Угорщина - дуже цікава країна з давньою і насиченою історією. І немає нічого дивного в тому, що її народ спілкується надзвичайно багатою мовою.
                    </p>
                    <a class="button" href="{% url 'blog:blog_post' slug='hungarian-language' %}">Читати</a>
                </div>
            </div>

            
        </div>
    </div>
    <!-- Blog Posts / End -->


    <!-- Widgets -->
    <div class="five columns blog">
       {% include 'blog/widget_sidebar_posts.html' %}
       <div class="clearfix"></div>
        <div class="margin-bottom-40"></div>
    </div><!-- Widgets / End -->


</div>
{%  endblock %}

{%  block custom_js %}
    <script>
        jQuery("#blog-link > a").attr('id', 'current');
    </script>
{%  endblock %}