blog/urls.py
from django.conf.urls import url

from .views import (
    home,
    blog_post,

)

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', blog_post, name="blog_post"),
    url(r'^$', home, name='home'),
]

employer/urls.py
from django.conf.urls import url

from .views.public import home, search_cv, post_job, recruitment
from .views.restricted import (
    cv_search,
    resume,
    my_vacancies,
    new_vacancy,
    edit_vacancy,
    vacancy_detail,
    vacancy_change_status,
    applications,
    pricing,
    profile,
    invoice,
    delete_acc_request,
    restore_acc_request,
    save_resume,
    app_details,
    app_archive,
    app_remove,
    app_refuse,

)

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^search-cv/$', search_cv, name='search_cv'),
    url(r'^add-job/$', post_job, name='post_job'),
    # restricted area
    url(r'^profile/$', profile, name='profile'),
    url(r'^invoice/(?P<num>\d+)/$', invoice, name='invoice'),

    url(r'^vacancies/new/$', new_vacancy, name='new_vacancy'),
    url(r'^vacancies/edit/(?P<pk>\d+)/$',
        edit_vacancy, name='edit_vacancy'),
    url(r'^vacancies/change-status/(?P<pk>\d+)/$',
        vacancy_change_status, name='change_status'),
    url(r'^vacancies/(?P<pk>\d+)/$', vacancy_detail, name='vacancy'),
    url(r'^my-vacancies/$', my_vacancies, name='my_vacancies'),

    url(r'^applications/(?P<vacancy_id>\d+)$',
        applications, name='applications'),
    url(r'^applications/details/(?P<pk>\d+)$',
        app_details, name='app_details'),
    url(r'^applications/archive/$', app_archive, name='app_archive'),
    url(r'^applications/remove/(?P<pk>\d+)/$',
        app_remove, name='app_remove'),
    url(r'^applications/refuse/(?P<pk>\d+)/$',
        app_refuse, name='app_refuse'),

    url(r'^cv-search/$', cv_search, name='cv_search'),
    url(r'^resume/(?P<pk>\d+)/$', resume, name='resume'),
    url(r'^pricing/$', pricing, name='pricing'),

    url(r'^profile/delete/(?P<pk>\d+)/$', delete_acc_request, name='del_acc'),
    url(r'^profile/restore/(?P<pk>\d+)/$',
        restore_acc_request, name='restore_acc'),
    url(r'^bookmark/(?P<action>(add)|(del))/(?P<pk>\d+)/$',
        save_resume, name='save_resume'),
    url(r'^recruitment/$', recruitment, name='recruitment'),
]

justjob5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    # url(r'^backoffice24/', include('backoffice24.urls',
    #     namespace='backoffice24')),
]


urlpatterns += i18n_patterns(
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^employer/', include('employer.urls', namespace='employer')),
    url(r'^', include('main_pages.urls', namespace='main')),
)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employer/models/categories.py
from django.db import models


class JobCategory(models.Model):
    title_en = models.CharField(
        max_length=77, blank=True, null=True, default='')
    title_hu = models.CharField(
        max_length=77, blank=True, null=True, default='')
    title_ru = models.CharField(
        max_length=77, blank=True, null=True, default='')
    title_uk = models.CharField(
        max_length=77, blank=True, null=True, default='')

    class Meta:
        verbose_name = "Job Category"
        verbose_name_plural = "Job Categories"

    def __str__(self):
        return self.title_en

employer/forms.py
from django import forms

from .models.profile import EmployerProfile
from .models.vacancies import Vacancy


class CompanyInfoForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='info')

    class Meta:
        model = EmployerProfile
        fields = [
            'short_title',
            'company_phones',
            'postal_address',
            'about_company',
            'website',
            'company_email',
            'linkedin_url',
            'logo',
            'form_name']


class CompanyPersonForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='person')

    class Meta:
        model = EmployerProfile
        fields = [
            'person_fullname',
            'person_position',
            'person_phone',
            'person_email',
            'form_name']


class CompanyBillingForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='billing')

    class Meta:
        model = EmployerProfile
        fields = [
            'full_title',
            'billing_address',
            'invoice_email',
            'bank_card',
            'iban',
            'vat_id',
            'eu_vat_id',
            'swift',
            'form_name']


class VacancyForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        fields = [
            'title',
            'phone_for_vac',
            'email_for_vac',
            'job_duties',
            'job_demands',
            'job_conditions',
            'job_description',
            'category',
            'job_type',
            'central_city',
            'location',
            'salary',
            'work_hours',
            'is_hot',
            'is_need_hu',
        ]


class MainLangForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='ml')

    class Meta:
        model = EmployerProfile
        fields = ['main_lang_ui']

employer/views/helpers.py
from employer.models.categories import JobCategory


def get_categories(lang='en'):
    categories = JobCategory.objects.all()
    categories_list = []
    for category in categories:
        if lang == 'ru':
            temp = (category.id, category.title_ru)
        elif lang == 'hu':
            temp = (category.id, category.title_hu)
        elif lang == 'uk':
            temp = (category.id, category.title_uk)
        else:
            temp = (category.id, category.title_en)
        categories_list.append(temp)
    return categories_list

employer/views/public.py
from django.shortcuts import render, redirect
from django.utils.translation import activate

from employer.models.prices import JobAddPrice, CvSearchPrice


def home(request):
    user = request.user or ''
    if user.is_authenticated and user.profile.user_role == 'employer':
        return redirect('employer:cv_search')
    return render(request, "employer/home.html", {})


def search_cv(request):
    cv_search_prices = CvSearchPrice.objects.filter(is_active=True)
    if request.LANGUAGE_CODE == 'ru':
        activate('ru')
    elif request.LANGUAGE_CODE == 'hu':
        activate('hu')
    elif request.LANGUAGE_CODE == 'uk':
        activate('uk')
    else:
        activate('en')
    return render(
        request,
        "employer/search_cv.html",
        {
            'items': cv_search_prices
        }
    )


def post_job(request):
    job_add_prices = JobAddPrice.objects.filter(is_active=True)
    return render(
        request,
        "employer/post_job.html",
        {
            'items': job_add_prices
        }
    )


def recruitment(request):
    prefix = 'en'
    if request.LANGUAGE_CODE == 'ru':
        prefix = 'ru'
    elif request.LANGUAGE_CODE == 'hu':
        prefix = 'hu'
    elif request.LANGUAGE_CODE == 'uk':
        prefix = 'uk'
    else:
        prefix = 'en'
    template = "employer/restricted/recruitment/{}.html".format(prefix)
    return render(request, template, {})

employer/views/restricted.py
import operator
from functools import reduce
from django.db.models import Q

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.utils.translation import activate


from justjob5.roles import is_employer
from employee.models import EmployeeProfile, Certificate

from employer.models.profile import (
    EmployerProfile, DeleteAccRequest, SavedResume)
from employer.models.vacancies import Vacancy
from employer.models.job_applications import (
    JobApplication, Comment, APP_STATUSES)
from employer.models.invoices import Invoice
from employer.models.prices import CvSearchPrice, JobAddPrice

from employer.forms import (
    CompanyInfoForm,
    CompanyPersonForm,
    CompanyBillingForm,
    VacancyForm,
    MainLangForm)

from employee.forms import MessageForm

from .helpers import get_categories


@login_required()
@is_employer
def my_vacancies(request):
    employer = get_object_or_404(EmployerProfile, user=request.user)
    active_vacs = Vacancy.objects.filter(
        company=employer, status='act').order_by('-updated_at')
    active_vacs_count = active_vacs.count()
    moder_vacs = Vacancy.objects.filter(
        company=employer, status='moder').order_by('-updated_at')
    moder_vacs_count = moder_vacs.count()
    draft_vacs = Vacancy.objects.filter(
        company=employer, status='draft').order_by('-updated_at')
    draft_vacs_count = draft_vacs.count()
    archive_vacs = Vacancy.objects.filter(
        company=employer, status='arch').order_by('-updated_at')
    archive_vacs_count = archive_vacs.count()
    return render(
        request,
        "employer/restricted/my_vacancies.html",
        {
            'active_vacs': active_vacs,
            'active_vacs_count': active_vacs_count,
            'moder_vacs': moder_vacs,
            'draft_vacs': draft_vacs,
            'archive_vacs': archive_vacs,
            'moder_vacs_count': moder_vacs_count,
            'draft_vacs_count': draft_vacs_count,
            'archive_vacs_count': archive_vacs_count,

        })


@login_required()
@is_employer
def vacancy_detail(request, pk=None):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    return render(
        request,
        "employer/restricted/vacancy.html",
        {
            'vacancy': vacancy
        })


@login_required()
@is_employer
def new_vacancy(request):
    if request.method == 'POST':
        form = VacancyForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            Vacancy.objects.create(
                title=form.data['title'],
                phone_for_vac=form.data['phone_for_vac'],
                email_for_vac=form.cleaned_data['email_for_vac'],
                job_duties=form.cleaned_data['job_duties'],
                job_demands=form.cleaned_data['job_demands'],
                job_conditions=form.cleaned_data['job_conditions'],
                job_description=form.cleaned_data['job_description'],
                central_city=form.cleaned_data['central_city'],
                location=form.cleaned_data['location'],
                salary=form.cleaned_data['salary'],
                work_hours=form.cleaned_data['work_hours'],
                is_hot=form.cleaned_data['is_hot'],
                is_need_hu=form.cleaned_data['is_need_hu'],
                status='draft',
                updated_by=request.user,
                job_type=form.cleaned_data['job_type'],
                category=form.cleaned_data['category'],
                company=get_object_or_404(
                    EmployerProfile, user=request.user.id),
            )
            return redirect('employer:my_vacancies')
    else:
        form = VacancyForm()
    return render(
        request,
        "employer/restricted/new_vacancy.html",
        {'form': form})


@login_required()
@is_employer
def edit_vacancy(request, pk=None):
    if pk:
        company = get_object_or_404(EmployerProfile, user=request.user.id)
        instance = Vacancy.objects.get(pk=pk, company=company)
    else:
        raise Http404
    form = VacancyForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False)
            Vacancy.objects.filter(pk=instance.id).update(
                title=form.data['title'],
                phone_for_vac=form.data['phone_for_vac'],
                email_for_vac=form.cleaned_data['email_for_vac'],
                job_duties=form.cleaned_data['job_duties'],
                job_demands=form.cleaned_data['job_demands'],
                job_conditions=form.cleaned_data['job_conditions'],
                job_description=form.cleaned_data['job_description'],
                central_city=form.cleaned_data['central_city'],
                location=form.cleaned_data['location'],
                salary=form.cleaned_data['salary'],
                work_hours=form.cleaned_data['work_hours'],
                is_hot=form.cleaned_data['is_hot'],
                is_need_hu=form.cleaned_data['is_need_hu'],
                status='draft',
                updated_at=timezone.now(),
                updated_by=request.user,
                job_type=form.cleaned_data['job_type'],
                category=form.cleaned_data['category'],
                company=company)
            return redirect('employer:my_vacancies')
    return render(
        request,
        "employer/restricted/edit_vacancy.html",
        {'form': form, 'title': instance.title, 'vac_id': instance.id})


@login_required()
@is_employer
def vacancy_change_status(request, pk):
    if pk:
        company = get_object_or_404(EmployerProfile, user=request.user.id)
        try:
            instance = Vacancy.objects.get(pk=pk, company=company)
        except:
            raise Http404
    if instance:
        status = instance.status
        if status == 'draft' or status == 'arch':
            Vacancy.objects.filter(pk=instance.id).update(status='moder')
        else:
            Vacancy.objects.filter(pk=instance.id).update(status='draft')
    return redirect('employer:my_vacancies')


@login_required()
@is_employer
def applications(request, vacancy_id=None):
    vacancy = get_object_or_404(Vacancy, pk=vacancy_id)
    applications = JobApplication.objects.filter(current_vacancy=vacancy)
    new_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='new')
    iv_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='iv')
    oe_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='oe')
    hir_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='hir')
    arc_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='arc')
    dis_apps = JobApplication.objects.filter(
        current_vacancy=vacancy, status='dis')
    return render(
        request,
        "employer/restricted/proposals.html",
        {
            'vacancy_id': vacancy_id,
            'vacancy_title': vacancy.title,
            'applications': applications,
            'new_apps': new_apps,
            'iv_apps': iv_apps,
            'oe_apps': oe_apps,
            'hir_apps': hir_apps,
            'arc_apps': arc_apps,
            'dis_apps': dis_apps,
            'new_apps_c': new_apps.count(),
            'iv_apps_c': iv_apps.count(),
            'oe_apps_c': oe_apps.count(),
            'hir_apps_c': hir_apps.count(),
            'arc_apps_c': arc_apps.count(),
            'dis_apps_c': dis_apps.count(),
        })


@login_required()
@is_employer
def app_details(request, pk=None):
    employer = get_object_or_404(EmployerProfile, user=request.user)
    prop = get_object_or_404(
        JobApplication, pk=pk, employer=employer)
    messages = Comment.objects.filter(
        application=prop).order_by('created_at')
    status_list = APP_STATUSES
    new_message = MessageForm()
    if request.method == 'POST' and request.POST.get('form_name') == 'send':
        new_message = MessageForm(request.POST)
        if new_message.is_valid():
            new_comment = Comment(
                application=prop,
                created_by=request.user,
                message=new_message.cleaned_data['message'])
            new_comment.save()
            return redirect('employer:app_details', pk=pk)
    if request.method == 'POST' and\
            request.POST.get('form_name') == 'change-status':
        cur_status = request.POST.get('status')
        prop.status = cur_status
        if cur_status == 'dis':
            prop.discarded_by_employer = True
        prop.save()
        return redirect('employer:app_details', pk=pk)

    return render(request, "employer/restricted/app_page.html", {
        'prop': prop,
        'messages': messages,
        'new_message': new_message,
        'status_list': status_list
    })


@login_required()
@is_employer
def app_refuse(request, pk=None):
    if pk and request.user.is_authenticated():
        employer = get_object_or_404(EmployerProfile, user=request.user)
        prop = get_object_or_404(
            JobApplication, pk=pk, employer=employer)
        prop.discarded_by_employer = True
        prop.status = 'arc'
        prop.save()
    return redirect('employer:app_details', pk=pk)


@login_required()
@is_employer
def app_archive(request, pk=None):
    pass


@login_required()
@is_employer
def app_remove(request, pk=None):
    pass


@login_required()
@is_employer
def profile(request):
    profile = get_object_or_404(EmployerProfile, user=request.user.id)
    logo = profile.logo or ''
    invoices = Invoice.objects.filter(invoiced_to=profile)
    form = CompanyInfoForm(instance=profile)
    form2 = CompanyPersonForm(instance=profile)
    form3 = CompanyBillingForm(instance=profile)
    form4 = MainLangForm(instance=profile)

employer/templates/employer/restricted/recruitment/en.html
{% extends "employer/employer_layout.html" %}
{% load i18n staticfiles %}

{%  block title %} {% trans 'Recruitment Services' %} - {{block.super}} {%  endblock %}


{%  block banner %}
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo-02.jpg' %});">
    <div class="container">

        <div class="ten columns">
            <h2>{% trans 'Recruitment Services' %}</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>{% trans 'You are here' %}:</li>
                    <li><a href="{% url 'employer:home' %}">{% trans 'For Employers' %}</a></li>
                    <li>{% trans 'Recruitment Services' %}</li>
                </ul>
            </nav>
        </div>

        

    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    <div class="sixteen columns">

        <ul>
            <li><h4>Do you need a larger number of staff?</h4></li>
            <li><h4>Do you have some specific requirements for the Ukrainian specialists you are looking for?</h4></li>
            <li><h4>And you don't want to impose on your employees with searching foreign talents?</h4></li>
            <li><h4>Let the JustJob team do it for you!</h4></li>
        </ul>
        <div class="margin-bottom-40"></div>
        <p>
            Within our Recruitment program, we are looking for qualified Ukrainian employees who are most suited to meet the requirements for the professional qualifications of our client.
        </p><p>
            Basing on our experience in the Ukrainian market, we will find the most suitable specialists for you in the shortest time. According to the client's requirements  we undertake the preliminary selection of candidates, interviews and necessary practical tests. At the end of the selection process, we will provide you with a range of most suitable candidates, as well as help you to get in direct contact with your future employees.
        </p><p>
            If you have not dealed with the employment of foreign specialists before, perhaps you might not to take into account all the necessary requirements and legal  actions for hiring employees from abroad, though this can significantly complicate the process of recruiting. You can entrust us to asssist you with the detailed information about the required documents (taxpayer number, TAJ number, work permit).
        </p>
            <h4>What is the cost of individual recruitment?</h4>
        <p>
            Our recruiting services for hiring the necessary staff for you are processed in accordance with a specific contract. The fee is determined individually for each case. After a detailed evaluation of the employer's expectations, we will provide an offer for the estimated cost of the tasks to be performed.
        </p><p>    
            Do not hesitate to contact us if you have any questions about employing a foreign worker – JustJob already has all answers!
        </p>
    </div>
</div>
        

{%  endblock %}



{%  block custom_js %}
    <script>
        jQuery("#recr-link > a").attr('id', 'current');
    </script>
{%  endblock %}

employer/templates/employer/restricted/recruitment/hu.html
{% extends "employer/employer_layout.html" %}
{% load i18n staticfiles %}

{%  block title %} {% trans 'Recruitment Services' %} - {{block.super}} {%  endblock %}


{%  block banner %}
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo-02.jpg' %});">
    <div class="container">

        <div class="ten columns">
            <h2>{% trans 'Recruitment Services' %}</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>{% trans 'You are here' %}:</li>
                    <li><a href="{% url 'employer:home' %}">{% trans 'For Employers' %}</a></li>
                    <li>{% trans 'Recruitment Services' %}</li>
                </ul>
            </nav>
        </div>

        

    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    <div class="sixteen columns">

        <ul>
            <li><h4>Nagyobb számú vendégmunkásra lenne szüksége?</h4></li>
            <li><h4>Egyedi elvárásai vannak a keresett ukrán szakemberrel kapcsolatosan?</h4></li>
            <li><h4>Nem szeretné munkatársait terhelni a külföldi munkavállalók kiválasztásával?</h4></li>
            <li><h4>Mi megkönnyítjük Önnek a megfelelő ukrán munkaerő megtalálását!</h4></li>
        </ul>
        <div class="margin-bottom-40"></div>
        <p>
 
            Munkaerő-közvetítési szolgáltatásunk keretében megbízónk speciális igényei alapján megkeressük a követelményeknek leginkább megfelelő szakképzett ukrán munkavállalókat, egyes szakmák esetében akár direkt keresés (fejvadászat) segítségével is. Ukrán piaci tapasztalatainkra támaszkodva rövid időn belül megtaláljuk Önnek a legalkalmasabb munkaerőt. Megbízói útmutatás alapján előszűrjük a jelentkezőket, lebonyolítjuk az interjúkat, elvégeztetjük a kért gyakorlati teszteket. A kiválasztási folyamat végén a legmegfelelőbb jelölteket részletesen bemutatjuk, segítünk a munkavállalókkal történő személyes kapcsolatfelvételben is.
        </p><p>
            Amennyiben Ön még nem alkalmazott külföldi munkaerőt, nem biztos, hogy tisztában van a jogszabályi előírásokkal és a szükséges teendőkkel. Mi ebben is segítünk, részletes tájékoztatást adunk a felmerülő feladatokról (adószám, TAJ-szám, engedélyek).
        </p><p>
            Munkaerő-közvetítési szolgáltatásunk igénybevétele egyedi szerződéskötés keretében történik, megbízási díj ellenében. Munkaerő igényének részletes felmérése után árajánlatot adunk Önnek az elvégzendő feladatokra vonatkozóan.
        </p><p>
            Vegye fel velünk a kapcsolatot, ha bármilyen kérdése merülne fel külföldi munkavállaló alkalmazásával kapcsolatosan, kollégáink részletes tájékoztatást adnak Önnek!   
        </p>
    </div>
</div>
        

{%  endblock %}



{%  block custom_js %}
    <script>
        jQuery("#recr-link > a").attr('id', 'current');
    </script>
{%  endblock %}

employer/templates/employer/restricted/recruitment/ru.html
{% extends "employer/employer_layout.html" %}
{% load i18n staticfiles %}

{%  block title %} {% trans 'Recruitment Services' %} - {{block.super}} {%  endblock %}


{%  block banner %}
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo-02.jpg' %});">
    <div class="container">

        <div class="ten columns">
            <h2>{% trans 'Recruitment Services' %}</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>{% trans 'You are here' %}:</li>
                    <li><a href="{% url 'employer:home' %}">{% trans 'For Employers' %}</a></li>
                    <li>{% trans 'Recruitment Services' %}</li>
                </ul>
            </nav>
        </div>

        

    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    <div class="sixteen columns">

        <ul>
            <li><h4>Вам нужно большое количество работников?</h4></li>
            <li><h4>У Вас есть определенные критерии или пожелания к уровню квалификации специалистов?</h4></li>
            <li><h4>Вам бы не хотелось озадачивать своих сотрудников поиском новых кадров?</h4></li>
            <li><h4>Мы упростим эту задачу!</h4></li>
        </ul>
        <div class="margin-bottom-40"></div>
        <p>

            В рамках нашей Экстра программы — «Подбор кадров» мы берем на себя поиск квалифицированных украинских сотрудников, которые наиболее соответствуют требованиям и пожеланиям нашего клиента.
        </p><p>
            Основываясь на нашем опыте работы на украинском рынке, мы в кратчайшие сроки найдем для Вас наиболее подходящих специалистов. Учитывая пожелания клиента, мы самостоятельно проводим предварительный подбор кандидатов, собеседования и необходимые практические тесты. По окончанию тщательного отбора мы предоставим заказчику подборку наиболее подходящих претендентов, а также поможем заранее обсудить все условия работы с будущими сотрудниками.
        </p><p>
            Если Вы еще не сталкивались с трудоустройством зарубежных специалистов, Вы можете не учесть всех правовых требований и необходимых действий, необходимых для найма сотрудников с заграницы, что может значительно усложнить процесс трудоустройства.
        </p><p>    
            Мы поможем Вам получить подробную информацию о необходимых документах (номер налогоплательщика, номер TAJ, разрешения на работу).
        </p>
            <h4>Какова стоимость индивидуального подбора персонала?</h4>
        <p>
            Услуги по поиску необходимых Вам кадров обрабатываются в соответствии с конкретным контрактом. Оплата услуг в каждом случае определяется индивидуально.
            После детальной оценки пожеланий работодателя, мы предоставим Вам предложение стоимости касательно выполняемых задач.
        </p><p>
            Свяжитесь с нами, если у Вас есть вопросы о тонкостях трудоустройства иностранного работника, и наши коллеги предоставят Вам подробную информацию!
        </p>
    </div>
</div>
        

{%  endblock %}



{%  block custom_js %}
    <script>
        jQuery("#recr-link > a").attr('id', 'current');
    </script>
{%  endblock %}

employer/templates/employer/restricted/recruitment/uk.html
{% extends "employer/employer_layout.html" %}
{% load i18n staticfiles %}

{%  block title %} {% trans 'Recruitment Services' %} - {{block.super}} {%  endblock %}


{%  block banner %}
<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/all-categories-photo-02.jpg' %});">
    <div class="container">

        <div class="ten columns">
            <h2>{% trans 'Recruitment Services' %}</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>{% trans 'You are here' %}:</li>
                    <li><a href="{% url 'employer:home' %}">{% trans 'For Employers' %}</a></li>
                    <li>{% trans 'Recruitment Services' %}</li>
                </ul>
            </nav>
        </div>

        

    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    <div class="sixteen columns">

        <ul>
            <li><h4>Вам потрібна велика кількість працівників?</h4></li>
            <li><h4>У Вас є певні критерії або побажання до рівня кваліфікації фахівців?</h4></li>
            <li><h4>Вам би не хотілося обтяжувати своїх співробітників пошуком нових кадрів?</h4></li>
            <li><h4>Ми спростимо цю задачу для Вас!</h4></li>
        </ul>
        <div class="margin-bottom-40"></div>
        <p>
            В рамках нашої Екстра програми «Підбір кадрів» ми беремо на себе пошук кваліфікованих українських робітників, які щонайбільше відповідають вимогам і побажанням нашого клієнта.
        </p><p>
            Грунтуючись на нашому досвіді роботи на українському ринку, ми в найкоротші терміни знайдемо для Вас найбільш підходящих фахівців. З огляду на побажання клієнта, ми самостійно проводимо попередній підбір кандидатів, співбесіди і необхідні практичні тести. По закінченню ретельного відбору ми надамо замовнику добірку найбільш підходящих претендентів, а також допоможемо в налагодити безпосередній контакт із майбутніми співробітниками.
        </p><p>
            Якщо Ви ще не зіштовхувалися з працевлаштуванням зарубіжних фахівців, Ви можете не врахувати всіх правових вимог і необхідних дій, необхідних для найму співробітників з-закордону, що може значно ускладнити процес працевлаштування.
        </p><p>    
            Ми допоможемо Вам отримати детальну інформацію про всі необхідні документи (номер платника податків, номер TAJ, дозволи на роботу).
        </p>
            <h4>Яка вартість індивідуального підбору персоналу?</h4>
        <p>
            Вартість послуг з пошуку необхідних Вам кадрів узгоджується відповідно до конкретного замовлення. Оплата послуг в кожному випадку визначається індивідуально. Після детальної оцінки побажань роботодавця, ми надамо Вам пропозицію вартості щодо виконуваних завдань.
        </p><p>
            Зв'яжіться з нами, якщо у Вас є питання про тонкощі працевлаштування іноземного працівника, і наші колеги нададуть Вам детальну інформацію!
        </p>
    </div>
</div>

{%  endblock %}



{%  block custom_js %}
    <script>
        jQuery("#recr-link > a").attr('id', 'current');
    </script>
{%  endblock %}