blog/urls.py
from django.conf.urls import url

from .views import (
    home,
    blog_post,

)

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', blog_post, name="blog_post"),
    url(r'^$', home, name='home'),
]

employee/urls.py
from django.conf.urls import url

from .views import (
    home,
    find_job,
    vacancies,
    job_page,
    add_resume,
    employers_view,
    employer,
    # restricted area
    profile,
    delete_cert,
    delete_acc_request,
    restore_acc_request,
    public_profile,
    save_job,
    proposals,
    proposals_archive,
    remove_proposal,
    proposal,
    proposal_refuse,
)

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^find-job/$', find_job, name='find_job'),
    url(r'^vacancies/$', vacancies, name='vacancies'),
    url(r'^add-resume/$', add_resume, name='add_resume'),
    url(r'^vacancy/(?P<pk>\d+)/$', job_page, name='vacancy'),
    url(r'^employers/$', employers_view, name='employers'),
    url(r'^employers/(?P<pk>\d+)/$', employer, name='employer'),

    # restricted area
    url(r'^profile/$', profile, name='profile'),
    url(r'^resume/(?P<pk>\d+)/$', public_profile, name='public_profile'),
    url(r'^profile/del-cert/(?P<pk>\d+)/$', delete_cert, name='del_cert'),
    url(r'^profile/delete/(?P<pk>\d+)/$', delete_acc_request, name='del_acc'),
    url(r'^profile/restore/(?P<pk>\d+)/$',
        restore_acc_request, name='restore_acc'),
    url(r'^bookmark/(?P<action>(add)|(del))/(?P<vac_id>\d+)/$',
        save_job, name='bookmark'),

    url(r'^proposals/$', proposals, name='proposals'),
    url(r'^proposals/archive/$', proposals_archive, name='proposals_archive'),
    url(r'^proposals/remove/(?P<pk>\d+)/$',
        remove_proposal, name='remove_proposal'),
    url(r'^proposal/refuse/(?P<pk>\d+)/$',
        proposal_refuse, name='proposal_refuse'),
    url(r'^proposal/(?P<pk>\d+)/$', proposal, name='proposal'),
]

justjob5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
    # url(r'^backoffice24/', include('backoffice24.urls',
    #     namespace='backoffice24')),
]


urlpatterns += i18n_patterns(
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^employer/', include('employer.urls', namespace='employer')),
    url(r'^', include('main_pages.urls', namespace='main')),
)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_pages/urls.py
from django.conf.urls import url

from .views import (
    home,
    contact,
    login_view,
    signup_view,
    logout_view,
    privacy,
    terms,
    usr_agr,
    cookies,

)

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^signup/$', signup_view, name='signup'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^contact/$', contact, name='contact'),

    url(r'^privacy/$', privacy, name='privacy'),
    url(r'^terms/$', terms, name='terms'),
    url(r'^user-agreement/$', usr_agr, name='usr_agr'),
    url(r'^cookies-policy/$', cookies, name='cookies'),

    url(r'^$', home, name='home'),
]

employee/forms.py
from django import forms

from .models import EmployeeProfile, Certificate
from employer.models.job_applications import JobApplication, Comment


class ProfileForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='profile')

    class Meta:
        model = EmployeeProfile
        fields = [
            'objective',
            'job_category',
            'experience',
            'education',
            'about_me',
            'level_of_en',
            'level_of_hu',
            'level_of_ru',
            'level_of_ua',
            'other_langs',
            'form_name']


class ContactForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='contact')

    class Meta:
        model = EmployeeProfile
        fields = [
            'full_name',
            'phone',
            'location_city',
            'location_country',
            'email',
            'skype',
            'linkedin_profile',
            'form_name']


class UploadCertForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='cert')

    class Meta:
        model = Certificate
        fields = [
            'title',
            'cert_file',
            'form_name']


class MainLangForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='ml')

    class Meta:
        model = EmployeeProfile
        fields = ['main_lang_ui', 'form_name']


class UploadPhotoForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='photo')

    class Meta:
        model = EmployeeProfile
        fields = ['photo', 'form_name']


class ResumeUploadForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='r1')

    class Meta:
        model = JobApplication
        fields = ['fullname', 'email', 'message', 'cv_file', 'current_vacancy']
        widgets = {'current_vacancy': forms.HiddenInput()}


class ResumeUpload2Form(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='r2')

    class Meta:
        model = JobApplication
        fields = ['message']


class MessageForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['message']

employee/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import activate

from justjob5.roles import is_employee

from employer.views.helpers import get_categories
from employer.models.vacancies import Vacancy
from employer.models.profile import EmployerProfile
from employer.models.job_applications import JobApplication, Comment

from .models import (
    EmployeeProfile, Certificate, DeleteAccRequest, Bookmark)

from .forms import (
    ContactForm,
    ProfileForm,
    UploadCertForm,
    MainLangForm,
    UploadPhotoForm,
    ResumeUploadForm,
    ResumeUpload2Form,
    MessageForm)


def home(request):
    user = request.user or ''
    if user.is_authenticated and user.profile.user_role == 'employee':
        return redirect('employee:vacancies')
    return render(request, "employee/home.html", {})


def add_resume(request):
    return render(request, "employee/add_resume.html", {})


def find_job(request):
    vacancies = Vacancy.objects.filter(status='act')[:20]
    hot_vacancies = Vacancy.objects.filter(
        status='act', is_hot=True).order_by('-updated_at')[:3]
    return render(request, "employee/find_job.html", {
        'vacancies': vacancies,
        'hot_vacancies': hot_vacancies
    })


def vacancies(request):
    categories = get_categories(request.LANGUAGE_CODE)
    vacancies = Vacancy.objects.filter(status='act')
    keywords = request.POST.get('keywords', '')
    category = request.POST.get('category', 'all')
    types = request.POST.getlist('jobType', ['any-type'])
    rates = request.POST.getlist('rate', ['any-rate'])
    if request.method == 'POST':
        if category != 'all':
            vacancies = vacancies.filter(category=category)
        if 'any-type' not in types:
            vacancies = vacancies.filter(job_type__in=types)

        if ['1', '2', '3'] == rates:
            rates = ['any-rate']
        print(rates)
        if 'any-rate' not in rates:
            if ['1', '2'] == rates:
                vacancies = vacancies.filter(salary__lt=25)
            else:
                if ['1'] == rates:
                    vacancies = vacancies.filter(salary__lte=10)
                elif ['2'] == rates:
                    vacancies = vacancies.filter(
                        Q(salary__lt=25) & Q(salary__gt=10))
            if ('3' in rates):
                if ['3'] == rates:
                    vacancies = vacancies.filter(salary__gte=25)
                if ['1', '3'] == rates:
                    vacancies = vacancies.filter(
                        Q(salary__lt=10) | Q(salary__gte=25))
                if ['2', '3'] == rates:
                    vacancies = vacancies.filter(salary__gt=10)

        vacancies = vacancies.filter(
            title__icontains=keywords).order_by('-published_at')
    return render(
        request,
        "employee/vacancies.html",
        {
            'categories': categories,
            'vacancies': vacancies,
            'keywords': keywords,
            'category': category,
            'types': types,
            'rates': rates
        })


@login_required()
@is_employee
def employers_view(request):
    keywords = request.POST.get('keywords', '')
    employers = EmployerProfile.objects.filter(is_active=True)
    if request.method == 'POST':
        employers = employers.filter(short_title__icontains=keywords)
    return render(request, "employee/restricted/employers.html", {
        'employers': employers,
        'keywords': keywords
    })


@login_required()
@is_employee
def employer(request, pk=None):
    employer = get_object_or_404(EmployerProfile, pk=pk)
    open_vacs = Vacancy.objects.filter(status='act', company=employer)
    return render(request, "employee/restricted/employer.html", {
        'employer': employer,
        'open_vacs': open_vacs
    })


@login_required()
@is_employee
def public_profile(request, pk=None):
    profile = get_object_or_404(EmployeeProfile, pk=pk)
    certs = Certificate.objects.filter(profile=profile, is_active=True)
    return render(
        request,
        "employee/restricted/public_profile.html",
        {'profile': profile, 'certificates': certs})


@login_required()
@is_employee
def profile(request):
    profile = get_object_or_404(EmployeeProfile, user=request.user.id)
    fullname = profile.full_name
    user_email = request.user.email
    photo = profile.photo or ''
    is_active = profile.is_active
    certificates = Certificate.objects.filter(profile=profile, is_active=True)
    form = ProfileForm(instance=profile)
    form2 = ContactForm(instance=profile)
    form3 = UploadCertForm()
    form4 = MainLangForm(instance=profile)
    form5 = UploadPhotoForm()
    saved_jobs = Bookmark.objects.filter(user=request.user)

    if request.method == 'POST' and request.POST.get('form_name') == 'profile':
        form = ProfileForm(request.POST, instance=profile)
        form.save(commit=False)
        form.objective = form.cleaned_data['objective']
        form.job_category = form.cleaned_data['job_category']
        form.experience = form.cleaned_data['experience']
        form.education = form.cleaned_data['education']
        form.about_me = form.cleaned_data['about_me']
        form.level_of_en = form.cleaned_data['level_of_en']
        form.level_of_hu = form.cleaned_data['level_of_hu']
        form.level_of_ru = form.cleaned_data['level_of_ru']
        form.level_of_ua = form.cleaned_data['level_of_ua']
        form.save()
        return HttpResponseRedirect('/employee/profile/#profile')

    if request.method == 'POST' and request.POST.get('form_name') == 'contact':
        form2 = ContactForm(request.POST, instance=profile)
        form2.save(commit=False)
        form2.full_name = form2.cleaned_data['full_name']
        form2.phone = form2.cleaned_data['phone']
        form2.location_city = form2.cleaned_data['location_city']
        form2.location_country = form2.cleaned_data['location_country']
        form2.email = form2.cleaned_data['email']
        form2.skype = form2.cleaned_data['skype']
        form2.linkedin_profile = form2.cleaned_data['linkedin_profile']
        form2.save()
        return HttpResponseRedirect('/employee/profile/#contacts')

    if request.method == 'POST' and request.POST.get('form_name') == 'cert':
        if request.FILES['cert_file']:
            form3 = UploadCertForm(request.POST, request.FILES)
            if form3.is_valid():
                new_cert = Certificate(
                    cert_file=request.FILES['cert_file'],
                    title=form3.cleaned_data['title'],
                    is_active=True,
                    profile=profile)
                new_cert.save()
                return HttpResponseRedirect('/employee/profile/#certs')

    if request.method == 'POST' and request.POST.get('form_name') == 'ml':
        form4 = MainLangForm(request.POST, instance=profile)
        if form4.is_valid():
            form4.save(commit=False)
            form4.main_lang_ui = form4.cleaned_data['main_lang_ui']
            try:
                activate(form4.main_lang_ui)
                print(form4.main_lang_ui)
            except:
                activate('en')
            form4.save()
        return redirect('employee:profile')

    if request.method == 'POST' and request.POST.get('form_name') == 'photo':
        if request.FILES['photo']:
            form5 = UploadPhotoForm(request.POST, request.FILES)
            if form5.is_valid():
                m = EmployeeProfile.objects.get(pk=profile.id)
                m.photo = form5.cleaned_data['photo']
                m.save()
            else:
                print(form5.errors)
            return redirect('employee:profile')

    return render(
        request,
        "employee/restricted/profile.html",
        {
            'fullname': fullname,
            'user_email': user_email,
            'photo': photo,
            'form': form,
            'form2': form2,
            'form3': form3,
            'form4': form4,
            'form5': form5,
            'certificates': certificates,
            'profile_id': profile.id,
            'is_active': is_active,
            'saved_jobs': saved_jobs
        })


@login_required()
@is_employee
def delete_cert(request, pk):
    if pk:
        candidate = get_object_or_404(EmployeeProfile, user=request.user.id)
        try:
            instance = Certificate.objects.get(pk=pk, profile=candidate)
        except:
            raise Http404
    if instance:
        Certificate.objects.filter(pk=instance.id).update(is_active=False)
    return redirect('employee:profile')


@login_required()
@is_employee
def delete_acc_request(request, pk):
    if pk:
        try:
            instance = get_object_or_404(
                EmployeeProfile, pk=pk, user=request.user.id)
        except:
            raise Http404
    if instance:
        EmployeeProfile.objects.filter(pk=instance.id).update(is_active=False)
        DeleteAccRequest.objects.create(
            profile=instance, canceled=False)
    return redirect('employee:profile')


@login_required()
@is_employee
def restore_acc_request(request, pk):
    if pk:
        try:
            instance = get_object_or_404(
                EmployeeProfile, pk=pk, user=request.user.id)
        except:
            raise Http404
    if instance:
        EmployeeProfile.objects.filter(pk=instance.id).update(is_active=True)
        DeleteAccRequest.objects.filter(
            profile=instance).update(canceled=True)
    return redirect('employee:profile')


def job_page(request, pk=None):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    form = ResumeUploadForm()
    form2 = ResumeUpload2Form()
    is_submitted = is_bookmarked = ''
    if request.user.is_authenticated():
        try:

employee/templates/employee/add_resume.html
{% extends "employee/employee_layout.html" %}
{% load i18n staticfiles %}

<title>{%  block title %} {% trans 'Add Resume' %} {{block.super}} {%  endblock %}</title>


{%  block titlebar %}

<div id="titlebar" class="photo-bg" style="background-image: url({% static 'images/add_resume.jpg' %});">
    <div class="container">
        <div class="ten columns">
            <h2>{% trans 'Add resume' %}</h2>
            <nav id="breadcrumbs">
                <ul>
                    <li>{% trans 'You are here' %}:</li>
                    <li><a href="{% url 'employee:home' %}">{% trans 'For Candidates' %}</a></li>
                    <li>{% trans 'Add resume' %}</li>
                </ul>
            </nav>
        </div>

    </div>
</div>
{%  endblock %}


{%  block content %}
<!-- Content
================================================== -->
<div class="container">
    
    <!-- Submit Page -->
    <div class="sixteen columns">
        <div class="submit-page margin-top-30 margin-bottom-55">
            
            <p>
                {% trans 'Do you want to increase your chances of working abroad?' %}<br>{% trans 'Upload your resume and let the employer find you!' %} 
            </p>
            <p>
                {% blocktrans %}Sign up, fill out your profile and upload your resume in native Ukrainian or Russian, and we will translate it and place it in our database in Hungarian. Employers will consider your candidacy in Hungarian and you will receive the desired response many times faster!{% endblocktrans %}
            </p>

            

        </div>
    </div>

</div>
<div class="clearfix"></div>
<div class="margin-bottom-55"></div>

<!-- Infobox -->
<div class="infobox">
    <div class="container">
        <div class="sixteen columns">{% trans 'Start Building Your Career in Europe Right Now' %} <a href="{% url 'main:login' %}">{% trans 'Get Started' %}</a></div>
    </div>
</div>
<!-- /Infobox -->

{%  endblock %}

{%  block custom_js %}
<!-- WYSIWYG Editor -->
<script src="{% static 'scripts/jquery.sceditor.bbcode.min.js' %}"></script>
<script src="{% static 'scripts/jquery.sceditor.js' %}"></script>

<script>
    jQuery("#add-resume-link > a").attr('id', 'current');
    jQuery(".infobox").css("marginBottom", "-40px");
</script>
{%  endblock %}

employee/templates/employee/home.html
{% extends "employee/employee_layout.html" %}
{% load i18n staticfiles %}

{%  block title %} {% trans 'For Candidates' %} {{block.super}} {%  endblock %}


{%  block banner %}
<div class="fullwidthbanner-container">
    <div class="fullwidthbanner">
        <ul>

            <!-- Slide 1 -->
            <li data-fstransition="fade" data-transition="fade" data-slotamount="10" data-masterspeed="300">

                <img src="{% static 'images/job_interview-03.jpg' %}" alt="" >

                <div class="caption title sfb" data-x="0" data-y="95" data-speed="400" data-start="800"  data-easing="easeOutExpo">
                    <h2>{% trans 'How often do you ask yourself' %}:</h2>
                </div>

                <div class="caption text sfb" data-x="0" data-y="170" data-speed="400" data-start="1200" data-easing="easeOutExpo">
                    <p>"{% trans 'Am I working on the right things?' %}"</p>
                </div>

                <div class="caption text sfb" data-x="0" data-y="270" data-speed="400" data-start="1400" data-easing="easeOutExpo">
                    <p>{% trans 'Maybe you are interested in working abroad?' %}</p>
                </div>

                <div class="caption text sfb" data-x="0" data-y="330" data-speed="400" data-start="1600" data-easing="easeOutExpo">
                    <p>{% trans 'Would you like to try your hand at another country?' %}</p>
                </div>

                <div class="caption text sfb" data-x="0" data-y="390" data-speed="400" data-start="1800" data-easing="easeOutExpo">
                    <p>{% trans 'Is that possible to find a reliable intermediary?' %}</p>
                </div>

            </li>

            <!-- Slide 2 -->
            <li data-transition="slideup" data-slotamount="10" data-masterspeed="800">
                <img src="{% static 'images/job_interview-05.jpg' %}" alt="">

                <div class="caption title sfb" data-x="center" data-y="195" data-speed="400" data-start="800"  data-easing="easeOutExpo">
                    <h2>{% trans 'Find vacancies in Europe and get hired!' %}</h2>
                </div>

                <div class="caption text align-center sfb" data-x="center" data-y="270" data-speed="400" data-start="1200" data-easing="easeOutExpo">
                    <p>{% trans 'Connect directly with the employers who want <br> to hire you.' %}</p>
                </div>

                <div class="caption sfb" data-x="center" data-y="400" data-speed="400" data-start="1600" data-easing="easeOutExpo">
                    <a href="{% url 'employee:find_job' %}" class="slider-button">{% trans 'Find Job' %}</a>
                    <a href="{% url 'employee:add_resume' %}" class="slider-button">{% trans 'Add Resume' %}</a>
                </div>
            </li>

        </ul>
    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    
    <!-- Submit Page -->
    <div class="sixteen columns">
        <div class="submit-page">


            <div class="margin-top-40 margin-bottom-20">
                <h3>{% trans 'How Justjob works?' %}</h3>
            </div>

            <p>
            {% trans 'Justjob is designed specifically for professionals from Ukraine looking for a  work abroad.' %}
            </p><p>{% blocktrans %}
            Our goal is to establish a direct connection between the Ukrainian specialist and a Hungarian employer, without any intermediaries.{% endblocktrans %}
            </p><p>{% blocktrans %}
            Are you interested in current job openings in Hungary? Here you will find various  job offers in both Ukrainian and Russian. You don`t have to know Hungarian language to browse jobs — we have already done the translation part for you!{% endblocktrans %}
            </p><p>{% blocktrans %}
            If there is no job offer that matches your qualification - upload your resume in native Ukrainian or Russian, and we will translate it into Hungarian. Thus, you get a great opportunity to find more vacancies from Hungarian employers, and choose the best offer for you.{% endblocktrans %}
            </p><p>{% blocktrans %}
            If you are interested in the employment and relocation to Europe —  do not hesitate to contact us. The Justjob team is always here to help you!{% endblocktrans %}
            </p>
        </div>
    </div>

</div>

<div class="clearfix margin-top-40"></div>

<!-- Infobox -->
<div class="infobox">
    <div class="container ">
        <div class="sixteen columns">{% trans 'Start Building Your Career in Europe Right Now' %}   <a href="{% url 'main:login' %}">{% trans 'Get Started' %}</a></div>
    </div>
</div>
<!-- /Infobox -->

{%  endblock %}

{%  block custom_js %}
    <script>
        jQuery("#home-link > a").attr('id', 'current');
        jQuery(".infobox").css("marginBottom", "-40px");
    </script>
{%  endblock %}

employee/templates/employee/job_page.html
{% extends "employee/employee_layout.html" %}
{% load i18n staticfiles form_tags %}

<title>{%  block title %} {{vacancy.title}} {{block.super}} {%  endblock %}</title>

{%  block banner %}

<div id="titlebar" class="photo-bg" style="background: url({% static 'images/job-page-photo.jpg' %})">
    <div class="container">
        <div class="ten columns">
            <span><a href="#">{{vacancy.category}}</a></span>
           <h2>{{ vacancy.title }}
                {% if vacancy.job_type == 'ft' %} 
                    <span class="full-time">{% trans 'Full-Time' %}</span>
                {% else %}
                    <span class="part-time">{% trans 'Part-Time' %}</span>
                {% endif %}
            </h2>
        </div>
        
        {% if user.is_authenticated and user.profile.user_role == 'employee' %}
        <div class="six columns">
            {% if is_bookmarked %}
                <a href="{% url 'employee:bookmark' action='del' vac_id=vacancy.pk %}" class="button white"><i class="fa fa-star-half-o"></i>{% trans 'Delete Bookmark' %} </a>
            {% else %}
                <a href="{% url 'employee:bookmark' action='add' vac_id=vacancy.pk %}" class="button white"><i class="fa fa-star"></i> {% trans 'Bookmark This Job' %}</a>
            {% endif %}
        </div>
        {% endif %}

    </div>
</div>

{%  endblock %}


{%  block content %}

<div class="container">
    
        <!-- Job -->
    <div class="eleven columns">
        <div class="padding-right">
            
            <!-- Company Info -->
            <div class="company-info">
                {% if  vacancy.image %}
                    <img src="{{ vacancy.image.url }}">
                {% else %}
                    <img src="{% static 'images/company.png' %}" alt="{{ vacancy.title }}">
                {% endif %}
                <div class="content">
                    <span>{% trans 'Vacancy' %}:</span>
                    <h4>{{ vacancy.title }}</h4>
                    <span>{{ vacancy.phone_for_vac|default_if_none:"" }}</span>
                    <span>{{ vacancy.email_for_vac|default_if_none:"" }}</span>
                </div>
                <div class="clearfix"></div>
            </div>

                        {% if vacancy.job_duties %}
                <div class="content">
                    <h4>{% trans 'Job Duties' %}:</h4>
                    <p>
                        {{ vacancy.job_duties|linebreaks }}
                    </p>
                </div>
                <br>
            {% endif %}
            
            {% if vacancy.job_demands %}
                <div class="content">
                    <h4>{% trans 'Job demands' %}:</h4>
                    <p>
                        {{ vacancy.job_demands|linebreaks }}
                    </p>
                </div>
                <br>
            {% endif %}
            
            {% if vacancy.job_conditions %}
                <div class="content">
                    <h4>{% trans 'Job conditions' %}:</h4>
                    <p>
                        {{ vacancy.job_conditions|linebreaks|safe }}
                    </p>
                </div>
            <br>
            {% endif %}
            {% if vacancy.job_description %}
                <div class="content">
                    <h4>{% trans 'Job description' %}:</h4>
                    <p>
                        {{ vacancy.job_description|linebreaks }}
                    </p>
                </div>
            {% endif %}

        </div>
    </div>

    <!-- Widgets -->
    <div class="five columns">

        <!-- Sort by -->
        <div class="widget">
            <h4>{% trans 'Overview' %}</h4>

            <div class="job-overview">
                
                 <ul>
                    <li>
                        <i class="fa fa-user"></i>
                        <div>
                            <strong>{% trans 'Employer' %}:</strong>
                            <span>
                                <a href="{% url 'employee:employer' pk=vacancy.company.id %}">
                                   {{vacancy.company.short_title|title}}
                                </a>
                            </span>
                        </div>
                    </li>
                    <li>
                        <i class="fa fa-map-marker"></i>
                        <div>
                            <strong>{% trans 'Location' %}:</strong>
                            {% if vacancy.central_city %}
                                <span>
                                    {{ vacancy.central_city|get_central_city }}
                            {% endif %}
                            {% if vacancy.location %}
                                ({{ vacancy.location|get_location|default_if_none:"" }})
                                </span>
                            {% endif %}
                        </div>
                                
                    </li>
                    {% if vacancy.work_hours %}
                    <li>
                        <i class="fa fa-clock-o"></i>
                        <div>
                            <strong>{% trans 'Work hours/week' %}:</strong>
                            <span>{{ vacancy.work_hours }}</span>
                        </div>
                    </li>
                    {% endif %}
                    {% if vacancy.salary %}
                    <li>
                        <i class="fa fa-money"></i>
                        <div>
                            <strong>{% trans 'Rate' %}:</strong>
                            <span>{{ vacancy.salary|get_currency }}</span>
                        </div>
                    </li>
                    {% endif %}
                </ul>

                {% if user.is_authenticated %}
                    {% if is_submitted %}
                        <p>{% trans 'You have already applied on this vacancy.' %}</p>
                    {% else %}
                        <a href="#small-dialog" class="popup-with-zoom-anim button">{% trans 'Apply For This Job' %}</a>
                    {% endif %}
                {% else %}
                    <a href="#small-dialog" class="popup-with-zoom-anim button">{% trans 'Apply For This Job' %}</a>
                {% endif %}
                
                <div id="small-dialog" class="zoom-anim-dialog mfp-hide apply-popup">
                    <div class="small-dialog-headline">
                        <h2>{% trans 'Apply For This Job' %}</h2>
                    </div>

                    <div class="small-dialog-content">
                            
                        {% if user.is_authenticated and not user.is_staff %}
                            <form method="post">
                                {% csrf_token %}
                                
                                {{ form2.as_p }}
                                <p>{% trans 'Resume will be attached from' %} <a href="{% url 'employee:profile' %}">{% trans 'Your profile' %}</a> {% trans 'automatically.' %}</p>
                        {% else %}
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                        {% endif %}

                            <div class="divider"></div>

                            <button type="submit" class="send">{% trans 'Send Resume' %}</button>
                        </form>
                    </div>
                    
                </div>

            </div>

        </div>

    </div><!-- Widgets / End -->


</div>

{%  endblock %}